name: Create EC2 instance

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  create-ec2-instance:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get GitHub token
      id: github-token
      uses: actions/github-script@v3
      with:
        script: |
          const response = await github.auth.createToken();
          console.log(`The token is: ${response.data.token}`);
          return response.data.token;

    - name: Configure AWS credentials
      run: |
        echo ${{ steps.github-token.outputs.token }} > token.json
        aws sts assume-role-with-web-identity \
          --role-arn arn:aws:iam::011974343726:role/admin-aws \
          --role-session-name ${{ github.actor }} \
          --web-identity-token file://token.json \
          --duration-seconds 3600
      env:
        AWS_REGION: us-east-1
        AWS_PROFILE: default

    - name: Create EC2 instance
      run: |
        aws ec2 run-instances \
          --image-id ami-01234567890abcdef0 \
          --instance-type t2.micro 
