name: Create EC2 instance

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  create-ec2-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Configure AWS credentials
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} > token.json
          aws sts assume-role-with-web-identity \
            --role-arn arn:aws:iam::ACCOUNT_ID:role/admin-aws \
            --role-session-name ${{ github.actor }} \
            --web-identity-token file://token.json \
            --duration-seconds 3600
        env:
          AWS_REGION: us-east-1
          AWS_PROFILE: default

      - name: Create EC2 instance
        run: |
          aws ec2 run-instances \
            --image-id ami-01234567890abcdef0 \
            --instance-type t2.micro
